version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: "docker"
    directory: "/.github/actions/build-and-deploy"
    schedule:
      interval: "daily"
