# Site settings
title:              Jose Diaz-Gonzalez
email:              support@savant.be
description:        'CakePHP Core Developer, Accidental Ops Guy, and Occasional Blogger'
author:             Jose Diaz-Gonzalez
baseurl:            ""
url:                http://josediazgonzalez.com
location:           'New York, New York'
navigation:         false

# ----------------------- #
#         Layouts         #
# ----------------------- #
# Anything specific to your layout can go here
related_limit:      false
excerpt_link:       "Read More&hellip;"

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

delicious_user:     darksavant0
delicious_count:    3
delicious_show:     true

disqus_shortname:   josediazgonzalez

facebook_user:      jose.diazgonzalez
facebook_show:      true
facebook_app_id:    775202682501320

flickr_user:        41296688@N07
flickr_show:        true

feedburner_name:

ga_tracking_id:     'UA-8668344-3'

github_user:        josegonzalez
github_repo:        josediazgonzalez.com
github_forkme:      false
github_show:        true

googleplus_user:
googleplus_show:    true

pinboard_user:      savant
pinboard_count: 3
pinboard_show:      true

twitter_user:       savant
twitter_show:       true

# ----------------------- #
#          Jekyll         #
# ----------------------- #
# All of these settings are required

# Set this to true to disable plugins
safe:               false
# Enables or disables Jekyll from recreating the site when files are modified.
regeneration:       true
# Changes the port that the Jekyll server will run on
port:               4000
# Sets site.url, useful for environment switching
url:                http://josediazgonzalez.com
# Changes the directory where Jekyll will look to transform files
source:             ./
# Changes the directory where Jekyll will write files to
destination:        _site
# Changes the directory where Jekyll will look for plugins
plugins_dir:        _plugins

# Inclusion of recent posts in sidebar
recent_posts:       false
# Inclusion/exclusion of future dated posts
future:             true
# Produces an index for related posts. Install rb-gsl and libgsl to speed this up
lsi:                false
# Uses [engine] instead of Maruku
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: false
  syntax_highlighter_opts:
    disable : true
highlighter: none
# Controls the URLs that posts are generated with.
permalink:          /:year/:month/:day/:title/
# A list of directories and files to exclude from the conversion
exclude:
  - bin
  - action-build
  - Gemfile
  - Gemfile.lock
  - Makefile
  - Rakefile
  - README.textile
  - requirements.txt
  - Vagrantfile
  - vendor
# A list of directories and files to include in the conversion
include:
  - .buildpacks
  - .nojekyll
  - .static
# Timezone for timestamp conversion
timezone: UTC


# ----------------------- #
#         Rakefile        #
# ----------------------- #
# This section holds Rakefile-specific configuration
# Contents subject to change

# SSH Connection info
ssh_user:           deploy@josediazgonzalez.com
# Port to connect with
ssh_port:           22
# Deploy path to sync _site directory to
deploy_path:        /apps/production/josediazgonzalez.com/current
# Port to serve
serve_port:         4000
# Default editor to use when creating new posts
editor:             subl
# Enable sharing
sharing:            false
# Enable comments
comments:           true
# Default category for new posts
category:           code
# Default format for new posts
format:             markdown
# Turn on redirection
redirects:          yes
