name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
      - name: Build and Deploy
        uses: ./.github/actions/build-and-deploy
