name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Deploy
        uses: ./.github/actions/build-and-deploy
        env:
          JEKYLL_GITHUB_ACCESS_TOKEN: ${{ secrets.JEKYLL_GITHUB_ACCESS_TOKEN }}
          SITE_REPOSITORY: josegonzalez/josegonzalez.github.io
          TRACE: 1
